version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8080"
    environment:
      - ENVIRONMENT=development
      - GOOGLE_CLOUD_PROJECT=your-project-id
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - LOG_LEVEL=DEBUG
    env_file:
      - .env
    depends_on:
      - firestore
    volumes:
      - ./src:/app/src:ro
    networks:
      - app-network

  firestore:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    command: gcloud emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8081:8080"
    networks:
      - app-network

  ngrok:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http app:8080
    ports:
      - "4040:4040"
    depends_on:
      - app
    networks:
      - app-network
    profiles:
      - ngrok

networks:
  app-network:
    driver: bridge